=== Muralikrishnan5971/RestAssuredFramework/target/classes/jsonSchemaFolder/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"id": {
			"type": "integer"
		},
		"firstname": {
			"type": "string"
		},
		"lastname": {
			"type": "string"
		},
		"email": {
			"type": "string"
		},
		"favfoods": {
			"type": "object",
			"properties": {
				"breakFast": {
					"type": "string"
				},
				"lunch": {
					"type": "string"
				},
				"dinner": {
					"type": "array",
					"items": [
						{
							"type": "string"
						},
						{
							"type": "string"
						}
					]
				}
			},
			"required": [
				"breakFast",
				"lunch",
				"dinner"
			]
		},
		"jobs": {
			"type": "array",
			"items": [
				{
					"type": "string"
				},
				{
					"type": "string"
				}
			]
		},
		"marks": {
			"type": "array",
			"items": [
				{
					"type": "object",
					"properties": {
						"tamil": {
							"type": "integer"
						},
						"english": {
							"type": "integer"
						}
					},
					"required": [
						"tamil",
						"english"
					]
				},
				{
					"type": "object",
					"properties": {
						"tamil": {
							"type": "integer"
						},
						"english": {
							"type": "integer"
						}
					},
					"required": [
						"tamil",
						"english"
					]
				}
			]
		}
	},
	"required": [
		"id",
		"firstname",
		"lastname",
		"email",
		"favfoods",
		"jobs",
		"marks"
	]
}

=== Muralikrishnan5971/RestAssuredFramework/responseJson/postNewEmployeeUsingExternalFileresponse.json
{
    "id": 1411,
    "firstname": "cletus",
    "lastname": "Jolie",
    "email": "iluvaj@gmail.com",
    "favfoods": {
        "breakFast": "Idly",
        "lunch": "Briyani",
        "dinner": [
            "pulka",
            "milk"
        ]
    },
    "jobs": [
        "manual qa",
        "automation tester"
    ],
    "marks": [
        {
            "tamil": 47,
            "english": 54
        },
        {
            "tamil": 69,
            "english": 85
        }
    ]
}
